required = ["github.com/golang/mock/mockgen"]

[[constraint]]
  branch = "master"
  name = "github.com/Clever/amazon-kinesis-client-go"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.34.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/mock"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.6.1"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.24.0"
